[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd web && npm install && npm run build"

[deploy]
startCommand = "cd web && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
